### PR TITLE
Add API documentation

### PR DESCRIPTION
**Pull request by bqqbarbhg**
My proposal for API documentation pipeline. API documentation is specified in `misc/api-template.md` and tagged comments near API endpoints in code. The docs are generated with https://github.com/bqqbarbhg/light-api-doc, we can move this under the ktk-2005 organization if we decide to use this. The API documentation needs to be manually generated using server-side `npm run doc`. The correctness of the API docs are tested on Travis, so basically one needs to run `npm run doc` when submitting a pull request.

Pros:
- Documentation is always in sync with the code, you can look at old / branched versions of the docs next to the code
- No need for external documentation server
- Documentation is browsable in GitHub: https://github.com/ktk-2005/Feedbacker-Forum/blob/api-doc/docs/api.md
- (subjective) I feel like free-form API documentation is more valuable than filling in tons of `@tags`

Cons:
- Need to manually do `npm run doc` to generate documentation
- Uses custom tool instead of a standard one

### CODE REVIEW

**Review by kalomak — DISMISSED** [review]
🤤👍

**Comment by bqqbarbhg** [comment]
Added support for automatically failing checks on missing API documentation

**Comment by HenrikHelenius** [comment]
Checked, nothing to comment, push others for new review, @Kallemakela the quickest for this

**Review by tobbe-j — COMMENTED** [review]
+1

**Review by tobbe-j — DISMISSED** [review]

**Review by tobbe-j — APPROVED** [review]
+1

**Pull request merged**
