### PR TITLE
Setup development environment

### PR DESCRIPTION
**Pull request by bqqbarbhg**
Set up the development environment...

Features:
- Babel compile pipeline for ES6
- ESLint configured with tweaked semicolonless Airbnb
- Webpack bundled React frontend
- Express backend with Mocha testing
- Automated testing with Travis CI

Some features for demonstration purposes:
- Single API endpoint `/api/version` which returns Git revision information
- Single React component displaying the version from the API
- Single API test for the version endpoint

For the testing environment I wrangled with Jest for a while but after failing to get it to work with Babel 7 I gave up and switched to Mocha.

### CODE REVIEW

**Comment by bqqbarbhg** [comment]
I tested it manually with clean checkout and IE11.

**Comment by joonalillfors** [comment]
Looking good

**Review by joonalillfors — APPROVED** [review]
Looking good

**Review by quvide — APPROVED** [review]
Looks good

**Pull request merged**
