### PR TITLE
Feature postgres

### PR DESCRIPTION
**Pull request by tobbe-j**
Added support for postgres database when running in production. Uses DATABASE_URL enviroment variable to connect to the database. 

Uses pg-promise package to communcate with postgres.

### CODE REVIEW

**Comment by bqqbarbhg** [comment]
SQLite doesn't support adding constraints in migrations :(
Should probably have flat spec for SQLite and migrations for Postgres.
If this gets too painful we can remove SQLite, but I would hope to keep it alive if we can with semi low effort

**Comment by tobbe-j** [comment]
Migrations for postgres and sqlite are now separated into different folders, is this enough?

**Comment by bqqbarbhg** [comment]
Yea looks good!

I would suggest renaming the SQLite migration just as `schema.sql` or something as it doesn't really support migrations well.

**Comment by bqqbarbhg** [comment]
The production Docker Travis CI tests should run with Postgres now right?

**Comment by bqqbarbhg** [comment]
Should we add distinction between query many vs query one?

**Review by bqqbarbhg — APPROVED** [review]
👍

**Comment by HenrikHelenius** [comment]
[(25/89) [task] [dynamic docker] Make dynamic docker Samuli](https://trello.com/c/LN926OBv/129-25-89-task-dynamic-docker-make-dynamic-docker-samuli)

**Pull request merged**
