### PR TITLE
Comment labels and comment thread fixes

### PR DESCRIPTION
**Pull request by tobbe-j**
- [x] OP labels
- [x] Dev labels - saved in blob
- [x] Doesn't post whitespace-only comments
- [x] Adds button to comment anonymously, on a per-comment basis
- [x] styling for anon button
- [x] Else?

### CODE REVIEW

**Comment by tobbe-j** [comment]
Were the emojis supposed to change or do we continue with these same emojis?

**Comment by tobbe-j** [comment]
[(5/5)[story] [comment view] As a user, I can disable my username from a comment when sending, so that I can comment anonymously even if I have input a name Tobias](https://trello.com/c/7doZ7rhu/106-5-5story-comment-view-as-a-user-i-can-disable-my-username-from-a-comment-when-sending-so-that-i-can-comment-anonymously-even-if)

**Comment by tobbe-j** [comment]
[(1/1)[task] Commenting doesn't allow whitespace only comments](https://trello.com/c/LwcYH6xC/165-1-1task-commenting-doesnt-allow-whitespace-only-comments)

**Comment by tobbe-j** [comment]
[(15/15) [story] [threading] As a user, I can comment on earlier comments, so that discussion is limited but possible. THREADS Tobias](https://trello.com/c/Jk4bbrlM/101-15-15-story-threading-as-a-user-i-can-comment-on-earlier-comments-so-that-discussion-is-limited-but-possible-threads-tobias)

**Review by bqqbarbhg — DISMISSED** [review]
Looking good

**Review by HenrikHelenius — APPROVED** [review]

**Review by HenrikHelenius — APPROVED** [review]

**Pull request merged**
