### PR TITLE
Readme sentence

### PR DESCRIPTION
**Pull request by bqqbarbhg**
I added a sentence to README.md

### CODE REVIEW

**Review by quvide — APPROVED** [review]
Great!

**Review by quvide — CHANGES_REQUESTED** [review]
Please merge to develop, not master

**Comment by HenrikHelenius** [comment]
[[task] [dod prep] Example Tobias](https://trello.com/c/BzDrNls2/38-task-dod-prep-example-tobias)

**Comment by quvide** [comment]
Closed due to this being more of a testing PR

**Pull request closed without merging**
